# Extension of the segmentation config with multi-class specific settings. Inherits from segmentation.yaml.
type: segmentation_mc

defaults:
  - segmentation
  - override /metrics@_global_.metrics: multi-class

lightning_module:
  _target_: dnanet.modules.segmentation.MultiClassSegmentationModule