# Training config for combined PeakNet
type: peaknet

defaults:
  - /metrics@_global_.metrics: multi-class

max_epochs: 100
batch_size: 16
learning_rate: 0.00012
weight_decay: 0.0005
val_fraction: 0.1
test_fraction: 0.0
num_workers: 7
seed: 42

optimizer:
  _target_: torch.optim.AdamW
  lr: ${train.learning_rate}
  weight_decay: ${train.weight_decay}

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.8
  optimizer: ${train.optimizer}

early_stopping:
  monitor: val/f1
  patience: 25
  min_delta: 0.00
  mode: max

checkpoint:
  monitor: val/f1
  save_top_k: 1
  mode: max

data_transform:
  _target_: dnanet.data.transformer.CombinedTransformer
  threshold: ${model.threshold}
  window_size: ${model.window_size}
  include_max_pool_dyes: ${model.include_max_pool_dyes}
  autoencoder_log_scale: ${model.autoencoder_log_scale}
  autoencoder_max_rfu: ${model.autoencoder_max_rfu}


lightning_module:
  _target_: dnanet.modules.peaknet.PeakNetModule
  learning_rate: ${train.learning_rate}
  weight_decay: ${train.weight_decay}
  loss_fn: ${model.loss}
  num_classes: ${model.architecture.num_classes}
  metrics:
    _target_: torchmetrics.MetricCollection
    metrics: ${metrics}
  batch_size: ${train.batch_size}

data_module:
  _target_: dnanet.data.datamodule.DNANetDataModule
  batch_size: ${train.batch_size}
  val_fraction: ${train.val_fraction}
  num_workers: ${train.num_workers}
  seed: ${train.seed}
  stratify_noc: ${oc.select:data.stratify_noc,false}
  group_by_replica: ${oc.select:data.group_by_replica,false}
