# Training hyperparameters for autoencoder reconstruction
type: reconstruction

defaults:
  - /metrics@_global_.metrics: mse

max_epochs: 150
batch_size: 128
learning_rate: 0.0001
weight_decay: 0.0
num_workers: 8
val_fraction: 0.2
test_fraction: 0.2
seed: 42

optimizer:
  _target_: torch.optim.AdamW
  lr: ${train.learning_rate}
  weight_decay: ${train.weight_decay}

# No LR scheduler by default for reconstruction
#scheduler:
#  _target_: torch.optim.lr_scheduler.ExponentialLR
#  gamma: 1.0  # effectively disabled
#  optimizer: ${train.optimizer}


early_stopping:
 monitor: val/mse
 patience: 8
 min_delta: 0.0
 mode: min

# Checkpointing
checkpoint:
  monitor: val/mse
  save_top_k: 1
  mode: min

lightning_module:
  _target_: dnanet.modules.reconstruction.ReconstructionModule
  learning_rate: ${train.learning_rate}
  weight_decay: ${train.weight_decay}
  loss_fn: ${model.loss}
  metrics:
    _target_: torchmetrics.MetricCollection
    metrics: ${metrics}
  autoencoder_log_scale: ${model.autoencoder_log_scale}
  autoencoder_max_rfu: ${model.autoencoder_max_rfu}
  batch_size: ${train.batch_size}

data_module:
  _target_: dnanet.data.datamodule.DNANetDataModule
  batch_size: ${train.batch_size}
  num_workers: ${train.num_workers}
