# @package _global_
defaults:
  - /evaluate: segmentation
  - _self_

task: evaluate


model:
  data_transform_active:
    _target_: dnanet.data.transformer.AlleleMetadataTransformer
    transformer: ${model.data_transform}
