accuracy:
  _target_: torchmetrics.classification.BinaryAccuracy
  threshold: .5
precision:
  _target_: torchmetrics.classification.BinaryPrecision
  threshold: .5
recall:
  _target_: torchmetrics.classification.BinaryRecall
  threshold: .5
f1:
  _target_: torchmetrics.classification.BinaryF1Score
  threshold: .5
jaccard_index:
  _target_: torchmetrics.classification.BinaryJaccardIndex
  threshold: .5
