_target_: torchmetrics.MetricCollection
metrics:
  precision:
    _target_: torchmetrics.classification.MulticlassPrecision
    num_classes: 12
  recall:
    _target_: torchmetrics.classification.MulticlassRecall
    num_classes: 12
  f1:
    _target_: torchmetrics.classification.MulticlassF1Score
    num_classes: 12
  jaccard_index:
    _target_: torchmetrics.classification.MulticlassJaccardIndex
    num_classes: 12