precision:
  _target_: torchmetrics.classification.MulticlassPrecision
  num_classes: ${data.num_classes}
  average: macro
recall:
  _target_: torchmetrics.classification.MulticlassRecall
  num_classes: ${data.num_classes}
  average: macro
f1:
  _target_: torchmetrics.classification.MulticlassF1Score
  num_classes: ${data.num_classes}
  average: macro
jaccard_index:
  _target_: torchmetrics.classification.MulticlassJaccardIndex
  num_classes: ${data.num_classes}
  average: macro
