# U-Net architecture for EPG segmentation
name: multiclass_unet

defaults:
  - /train@_global_.train: multiclass_segmentation


architecture:
  _target_: dnanet.models.unet.UNet
  depth: 4
  kernel_size: [3, 5]
  num_filters: 32
  out_channels: ${data.num_classes}

loss:
  _target_: torch.nn.CrossEntropyLoss
  ignore_index: null

data_transform:
  _target_: dnanet.data.transformer.SegmentationTransformer

